" ========================
" LazyVim-Inspired _vimrc
" ========================

" Line numbers
set number
set relativenumber

" Clipboard
set clipboard=unnamed

" Leader key
let mapleader = " "

" Highlight search
set hlsearch
set incsearch
nnoremap <Esc> <Esc>:nohlsearch<CR>

" Esc (So I can exit peeks and clear highlight searches with C-[)
nnoremap <C-[> <Esc>:nohlsearch<CR>

" Save file
" nnoremap <silent> <C-s> :w<CR>
" inoremap <silent> <C-s> <Esc>:w<CR>a

" Buffer navigation
nnoremap <leader>bb :ls<CR>:b<Space>
nnoremap <leader>bd :bd<CR>
nnoremap <leader>bo :bufdo bd<CR>

" Window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Window resizing
nnoremap <C-Up>    :resize +2<CR>
nnoremap <C-Down>  :resize -2<CR>
nnoremap <C-Left>  :vertical resize -2<CR>
nnoremap <C-Right> :vertical resize +2<CR>

" Tab navigation
nnoremap <S-h> :vsc Window.PreviousTab<CR>
nnoremap <S-l> :vsc Window.NextTab<CR>

" Move lines up/down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" Search navigation
nnoremap n nzz
nnoremap N Nzz

" Scroll and center
nnoremap <C-u> <C-u>zz
nnoremap <C-d> <C-d>zz

" Clear search highlight
nnoremap <leader><Esc> :nohlsearch<CR>

" Find files
nnoremap <leader><leader> :vsc Edit.GoToFile<CR>

" Toggle Solution Explorer
nnoremap <leader>e :vsc View.SolutionExplorer<CR>

" Go to Definition
nnoremap gd :vsc Edit.GoToDefinition<CR>

" Go to Implementation
nnoremap gi :vsc Edit.GoToImplementation<CR>

" Go to References
nnoremap gr :vsc Edit.FindAllReferences<CR>

" Peek Definition (like hovering or inline preview)
nnoremap gp :vsc Edit.PeekDefinition<CR>

" Quick info
nnoremap <S-k> :vsc Edit.QuickInfo<CR>

" Refactoring
vnoremap <leader>rs :vsc Refactor.Rename<CR>

" --- Folding (use defaults; no redundant self-maps) ---
" za  toggle under cursor
" zR  open all folds
" zM  close all folds
" zo  open one fold
" zc  close one fold

" Diagnostics (mocked)
nnoremap <leader>cd :echo "Show diagnostics"<CR>
nnoremap <leader>cf :echo "Format code"<CR>

" Tabs (mocked)
nnoremap <leader><Tab>n :tabnew<CR>
nnoremap <leader><Tab>d :tabclose<CR>
nnoremap <leader><Tab>l :tabnext<CR>
nnoremap <leader><Tab>h :tabprevious<CR>

" Toggle options
nnoremap <leader>uw :set wrap!<CR>
nnoremap <leader>ul :set number!<CR>
nnoremap <leader>uL :set relativenumber!<CR>

" Visual Indent Blocks
vmap > >gv
vmap < <gv

" Comments
" Toggle line comment on current line
nnoremap gcc :vsc Edit.ToggleLineComment<CR>
" Toggle comment for visual selection
vnoremap gc :vsc Edit.ToggleBlockComment<CR>

" Close current buffer/document
nnoremap <leader>bd :vsc File.Close<CR>

" Close all but current (approx.)
nnoremap <leader>bo :vsc Window.CloseAllButThis<CR>

" Git Blame (VS shows blame in Git Changes or inline)
nnoremap <leader>gb :vsc View.GitRepositoryWindow<CR>

" Git Browse (open in browser)
nnoremap <leader>gB :vsc File.ViewinBrowser<CR>

" Git Diff (current file vs HEAD)
nnoremap <leader>gd :vsc Git.CompareWithUnmodified<CR>

" Git Diff (origin) – VS uses Compare with Branch
nnoremap <leader>gD :vsc Git.CompareWithBranch<CR>

" Git Current File History
nnoremap <leader>gf :vsc Git.ViewFileHistory<CR>

" Lazygit equivalent – open Git Changes window
nnoremap <leader>gg :vsc View.GitChanges<CR>

" Git Log (solution)
nnoremap <leader>gl :vsc Git.ViewHistory<CR>

" Toggle options (LazyVim-like UX toggles) ---
nnoremap <leader>uw :set wrap!<CR>
nnoremap <leader>ul :set number!<CR>
nnoremap <leader>uL :set relativenumber!<CR>

"Toggle Error List (LazyVim uses <leader>xx for Trouble)
" This opens Visual Studio's Error List window
nnoremap <leader>xx :vsc View.ErrorList<CR>

" Toggle Task List (similar to Quickfix list in Vim)
" This opens Visual Studio's Task List window
nnoremap <leader>xq :vsc View.TaskList<CR>
